version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - exclusive-frontend:/app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - chat_app_network
    command: npm start
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file: 
      - ./backend/env/backend.env
    volumes:
      - ./backend:/app
      - exclusive-backend:/app/node_modules
    ports:
      - 8000:80
    networks: 
      - chat_app_network
    depends_on: 
      - database
    command: npm run dev
  database:
    container_name: mongo
    image: mongo
    env_file: 
      - ./database/env/database.env
    volumes: 
      - ./database/data:/data/db
    ports: 
      - 27017:27017
    restart: always
    networks: 
      - chat_app_network

volumes: 
  exclusive-frontend:
  exclusive-backend:
networks: 
  chat_app_network: