version: '3.7'

services:
  backend:
    container_name: chat_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./backend/env/backend.env
    volumes:
      - ./backend:/app
      - chat_app_backend_node_modules:/app/node_modules
    ports:
      - 8000:80
    networks: 
      - chat_app_network
    depends_on: 
      - database
    command: npm run dev
  database:
    container_name: mongo
    image: mongo
    env_file: 
      - ./database/env/database.env
    volumes: 
      - ./database/data:/data/db
    ports: 
      - 27017:27017
    restart: always
    networks: 
      - chat_app_network

volumes: 
  chat_app_backend_node_modules:
networks: 
  chat_app_network: